filebeat.inputs:
  - type: filestream
    id: app-json-logs
    enabled: true
    paths:
      - /var/logs/json/*.json
      - /var/logs/json/*.log
    parsers:
      - ndjson:
          overwrite_keys: true
          add_error_key: true
    fields:
      source: "filebeat-fallback"
      service: "logsentry-api"
    fields_under_root: true
    ignore_older: 72h

# Logstash 로 전송 (Kafka 장애 시에도 파일에서 수집)
output.logstash:
  hosts: ["logstash:5044"]

queue.mem:
  events: 8192
  flush.min_events: 512
  flush.timeout: 5s

logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 3
  permissions: 0644
