spring:
  application:
    name: logsentry-api

logging:
  file:
    path: ./logs
  level:
    root: INFO
    com.nana.logsentry: INFO

server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
      export:
        enabled: true
